In [1]:
data = {'ID': 1, 'Name': 'Alice', 'Age': 25}
data

{'ID': 1, 'Name': 'Alice', 'Age': 25}

In [2]:
type(data)

dict

In [4]:
print(len(data))

3


In [5]:
import polars as pl
#pl.show_versions()
df = pl.DataFrame(data)
df

ID,Name,Age
i64,str,i64
1,"""Alice""",25


In [6]:
type(df)

polars.dataframe.frame.DataFrame

In [7]:
df.columns

['ID', 'Name', 'Age']

In [8]:
len(df)

1

In [10]:
n_data = [[1, 'Alice', 25]]
print(n_data)
print(len(n_data))
print(type(n_data))

[[1, 'Alice', 25]]
1
<class 'list'>


In [14]:
df = pl.DataFrame(n_data, schema=['ID', 'Name', 'Age'], orient="row")
df

ID,Name,Age
i64,str,i64
1,"""Alice""",25


In [16]:
print(type(df))
print(len(df))

<class 'polars.dataframe.frame.DataFrame'>
1


In [17]:
c_data = {
    'Scores': [[85, 90, 95], [88, 82, 75], [84, 98, 92]],
    'Name': ['Alice',  'Bob', 'Charlie'],
    'Age': [25, 36, 35],
    'Details': [
        {"City": 'New York', 'job': "Engineer"},
        {"City": 'LoasAngeles', 'job': "Artist"},
        {"City": 'chicago', 'job': "Doctor"}
    ]
}

In [23]:
import pandas as pd
df_pandas = pd.DataFrame(c_data)
print(df_pandas.dtypes)
print(type(df_pandas))
df_pandas

Scores     object
Name       object
Age         int64
Details    object
dtype: object
<class 'pandas.core.frame.DataFrame'>


,Scores,Name,Age,Details
0,"[85, 90, 95]",Alice,25,"{'City': 'New York', 'job': 'Engineer'}"
1,"[88, 82, 75]",Bob,36,"{'City': 'LoasAngeles', 'job': 'Artist'}"
2,"[84, 98, 92]",Charlie,35,"{'City': 'chicago', 'job': 'Doctor'}"


In [24]:
df_polars = pl.DataFrame(c_data)
print(type(df_polars))
df_polars

<class 'polars.dataframe.frame.DataFrame'>


Scores,Name,Age,Details
list[i64],str,i64,struct[2]
"[85, 90, 95]","""Alice""",25,"{""New York"",""Engineer""}"
"[88, 82, 75]","""Bob""",36,"{""LoasAngeles"",""Artist""}"
"[84, 98, 92]","""Charlie""",35,"{""chicago"",""Doctor""}"


In [26]:
df_from_pandas = pl.from_pandas(df_pandas)
print(type(df_from_pandas))
df_from_pandas

<class 'polars.dataframe.frame.DataFrame'>


Scores,Name,Age,Details
list[i64],str,i64,struct[2]
"[85, 90, 95]","""Alice""",25,"{""New York"",""Engineer""}"
"[88, 82, 75]","""Bob""",36,"{""LoasAngeles"",""Artist""}"
"[84, 98, 92]","""Charlie""",35,"{""chicago"",""Doctor""}"


In [27]:
df_to_pandas = df_polars.to_pandas()
print(type(df_to_pandas))
df_to_pandas

<class 'pandas.core.frame.DataFrame'>


,Scores,Name,Age,Details
0,"[85, 90, 95]",Alice,25,"{'City': 'New York', 'job': 'Engineer'}"
1,"[88, 82, 75]",Bob,36,"{'City': 'LoasAngeles', 'job': 'Artist'}"
2,"[84, 98, 92]",Charlie,35,"{'City': 'chicago', 'job': 'Doctor'}"


In [29]:
#LAZY
df = pl.DataFrame({"name": ["Alice", "Bob", "Charlie"], "age": [25, 30, 35]})
lazy_df = df.lazy() # Convert to lazy mode 
filtered_lazy_df = lazy_df.filter(pl.col("age") > 28) # No execution yet! 
result = filtered_lazy_df.collect() 
print(result)
print(type(result))

shape: (2, 2)
┌─────────┬─────┐
│ name    ┆ age │
│ ---     ┆ --- │
│ str     ┆ i64 │
╞═════════╪═════╡
│ Bob     ┆ 30  │
│ Charlie ┆ 35  │
└─────────┴─────┘
<class 'polars.dataframe.frame.DataFrame'>


# Why Use Lazy Mode?
- Faster Execution: Polars avoids unnecessary computations, making it faster for large datasets.
- Better Memory Management: It processes data in chunks instead of keeping everything in memory.
- Smart Query Optimization: It can rearrange operations for better efficiency, like pushing filters earlier to reduce the amount of data processed.

## When to Use Lazy Mode?
- Working with large datasets (millions or billions of rows).
- Running complex queries involving multiple operations.
- Needing efficient memory usage to avoid crashes.

In [31]:
csv_path = './Files/Sample_Superstore.csv'
csv_df = pl.read_csv(csv_path)
csv_df

Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit
i64,str,str,str,str,str,str,str,str,str,str,i64,str,str,str,str,str,f64,i64,f64,f64
1,null,null,"""11-11-2016""","""Second Class""","""CG-12520""","""Claire Gute""","""Consumer""","""United States""","""Henderson""","""Kentucky""",42420,"""South""","""FUR-BO-10001798""","""Furniture""","""Bookcases""","""Bush Somerset Collection Bookc…",261.96,2,0.0,41.9136
2,"""CA-2016-152156""","""08-11-2016""","""11-11-2016""","""Second Class""","""CG-12520""","""Claire Gute""","""Consumer""","""United States""","""Henderson""","""Kentucky""",42420,"""South""","""FUR-CH-10000454""","""Furniture""","""Chairs""","""Hon Deluxe Fabric Upholstered …",731.94,3,0.0,219.582
3,"""CA-2016-138688""","""12-06-2016""",null,null,"""DV-13045""","""Darrin Van Huff""","""Corporate""",null,"""Los Angeles""","""California""",90036,"""West""","""OFF-LA-10000240""","""Office Supplies""","""Labels""","""Self-Adhesive Address Labels f…",14.62,2,0.0,6.8714
4,null,"""11-10-2015""",null,"""Standard Class""","""SO-20335""","""Sean O'Donnell""","""Consumer""","""United States""","""Fort Lauderdale""","""Florida""",33311,"""South""","""FUR-TA-10000577""","""Furniture""","""Tables""","""Bretford CR4500 Series Slim Re…",957.5775,5,0.45,-383.031
5,"""US-2015-108966""","""11-10-2015""","""18-10-2015""","""Standard Class""","""SO-20335""","""Sean O'Donnell""","""Consumer""","""United States""",null,"""Florida""",33311,"""South""","""OFF-ST-10000760""","""Office Supplies""","""Storage""","""Eldon Fold 'N Roll Cart System""",22.368,2,0.2,2.5164
…,…,…,…,…,…,…,…,…,…,…,…,…,…,…,…,…,…,…,…,…
9990,"""CA-2014-110422""","""21-01-2014""","""23-01-2014""","""Second Class""","""TB-21400""","""Tom Boeckenhauer""","""Consumer""","""United States""","""Miami""","""Florida""",33180,"""South""","""FUR-FU-10001889""","""Furniture""","""Furnishings""","""Ultra Door Pull Handle""",25.248,3,0.2,4.1028
9991,"""CA-2017-121258""","""26-02-2017""","""03-03-2017""","""Standard Class""","""DB-13060""","""Dave Brooks""","""Consumer""","""United States""","""Costa Mesa""","""California""",92627,"""West""","""FUR-FU-10000747""","""Furniture""","""Furnishings""","""Tenex B1-RE Series Chair Mats …",91.96,2,0.0,15.6332
9992,"""CA-2017-121258""","""26-02-2017""","""03-03-2017""","""Standard Class""","""DB-13060""","""Dave Brooks""","""Consumer""","""United States""","""Costa Mesa""","""California""",92627,"""West""","""TEC-PH-10003645""","""Technology""","""Phones""","""Aastra 57i VoIP phone""",258.576,2,0.2,19.3932


In [32]:
print(type(csv_df))

<class 'polars.dataframe.frame.DataFrame'>


In [33]:
csv_df['Profit'].head()

Profit
f64
41.9136
219.582
6.8714
-383.031
2.5164
14.1694
1.9656
90.7152
5.7825


In [35]:
print(type(csv_df['Profit'].head()))

<class 'polars.series.series.Series'>


In [36]:
csv_df.select('Profit').to_series().head(3)

Profit
f64
41.9136
219.582
6.8714


In [37]:
s = csv_df['Customer_Name']
s.to_frame().head(3)

Customer_Name
str
"""Claire Gute"""
"""Claire Gute"""
"""Darrin Van Huff"""


In [38]:
s

Customer_Name
str
"""Claire Gute"""
"""Claire Gute"""
"""Darrin Van Huff"""
"""Sean O'Donnell"""
"""Sean O'Donnell"""
…
"""Tom Boeckenhauer"""
"""Dave Brooks"""
"""Dave Brooks"""


# Series or Dataframe from `list` or `dict`

In [39]:
val = [1,2,3]
print(val, type(val))

[1, 2, 3] <class 'list'>


In [41]:
pl.Series(val)

""
i64
1
2
3


In [42]:
pl.Series('vals', val)

vals
i64
1
2
3


In [43]:
pl.Series(name='vals', values=val).to_list()

[1, 2, 3]

In [44]:
import numpy as np

csv_df.to_numpy()

array([[1, None, None, ..., 2, 0.0, 41.9136],
       [2, 'CA-2016-152156', '08-11-2016', ..., 3, 0.0, 219.582],
       [3, 'CA-2016-138688', '12-06-2016', ..., 2, 0.0, 6.8714],
       ...,
       [9992, 'CA-2017-121258', '26-02-2017', ..., 2, 0.2, 19.3932],
       [9993, 'CA-2017-121258', '26-02-2017', ..., 4, 0.0, 13.32],
       [9994, 'CA-2017-119914', '04-05-2017', ..., 2, 0.0, 72.948]],
      shape=(9994, 21), dtype=object)

In [46]:
f_array = csv_df.select(pl.col(pl.Float64)).to_numpy()
f_array

array([[2.61960e+02, 0.00000e+00, 4.19136e+01],
       [7.31940e+02, 0.00000e+00, 2.19582e+02],
       [1.46200e+01, 0.00000e+00, 6.87140e+00],
       ...,
       [2.58576e+02, 2.00000e-01, 1.93932e+01],
       [2.96000e+01, 0.00000e+00, 1.33200e+01],
       [2.43160e+02, 0.00000e+00, 7.29480e+01]], shape=(9994, 3))

In [48]:
l_df = pl.DataFrame(f_array.tolist())
print(type(l_df))
l_df

<class 'polars.dataframe.frame.DataFrame'>


column_0,column_1,column_2,column_3,column_4,column_5,column_6,column_7,column_8,column_9,column_10,column_11,column_12,column_13,column_14,column_15,column_16,column_17,column_18,column_19,column_20,column_21,column_22,column_23,column_24,column_25,column_26,column_27,column_28,column_29,column_30,column_31,column_32,column_33,column_34,column_35,column_36,…,column_9957,column_9958,column_9959,column_9960,column_9961,column_9962,column_9963,column_9964,column_9965,column_9966,column_9967,column_9968,column_9969,column_9970,column_9971,column_9972,column_9973,column_9974,column_9975,column_9976,column_9977,column_9978,column_9979,column_9980,column_9981,column_9982,column_9983,column_9984,column_9985,column_9986,column_9987,column_9988,column_9989,column_9990,column_9991,column_9992,column_9993
f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,…,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64,f64
261.96,731.94,14.62,957.5775,22.368,48.86,7.28,907.152,18.504,114.9,1706.184,911.424,15.552,407.976,68.81,2.544,665.88,55.5,8.56,213.48,22.72,19.46,60.34,71.372,1044.63,11.648,90.57,3083.43,9.618,124.2,3.264,86.304,6.858,15.76,29.472,1097.544,190.92,…,223.92,7.3,9.344,18.0,65.584,383.4656,10.368,13.4,4.98,109.69,40.2,735.98,22.75,119.56,140.75,99.568,271.96,18.69,13.36,249.584,13.86,13.376,437.472,85.98,16.52,35.56,97.98,31.5,55.6,36.24,79.99,206.1,25.248,91.96,258.576,29.6,243.16
0.0,0.0,0.0,0.45,0.2,0.0,0.0,0.2,0.2,0.0,0.2,0.2,0.2,0.2,0.8,0.8,0.0,0.0,0.0,0.2,0.2,0.0,0.0,0.3,0.0,0.2,0.0,0.5,0.7,0.2,0.2,0.2,0.7,0.2,0.2,0.2,0.6,…,0.0,0.0,0.2,0.0,0.2,0.32,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.2,0.0,0.0,0.2,0.0,0.2,0.2,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.0,0.2,0.0,0.0
41.9136,219.582,6.8714,-383.031,2.5164,14.1694,1.9656,90.7152,5.7825,34.47,85.3092,68.3568,5.4432,132.5922,-123.858,-3.816,13.3176,9.99,2.4824,16.011,7.384,5.0596,15.6884,-1.0196,240.2649,4.2224,11.7741,-1665.0522,-7.0532,15.525,1.1016,9.7092,-5.715,3.546,9.9468,123.4737,-147.963,…,109.7208,2.19,1.8688,3.24,23.7742,-67.6704,3.6288,6.432,2.3406,51.5543,18.09,331.191,6.5975,54.9976,42.225,33.6042,27.196,5.2332,6.4128,31.198,0.0,4.6816,153.1152,22.3548,5.369,16.7132,27.4344,15.12,16.124,15.2208,28.7964,55.647,4.1028,15.6332,19.3932,13.32,72.948


In [49]:
csv_df['Profit'].to_numpy()#zero copy = read only possible if no nan or null is present

array([ 41.9136, 219.582 ,   6.8714, ...,  19.3932,  13.32  ,  72.948 ],
      shape=(9994,))

In [50]:
csv_df['Profit'].to_numpy(allow_copy=False) #fails

RuntimeError: copy not allowed: cannot convert to a NumPy array without copying data

*allow_copy=True (Default): Polars extracts data as a zero-copy view if possible. If the data layout requires adjustments (like merging multi-chunk columns or rewriting data types), it will quietly clone the data in memory to build the array.allow_copy=False: Polars will only succeed if it can point NumPy directly to its existing Apache Arrow memory structures without duplication. If a copy is required, it immediately throws an exception*

# Data types

In [51]:
df = pl.DataFrame({
    "integer_column": [1, 2, 3, 4, 5],  # Default: Int64
    "float_column": [1.1, 2.2, 3.3, 4.4, 5.5]  # Default: Float64
})
 
print("DataFrame:")
print(df)
 
print("\nData Types:")
print(df.schema)


DataFrame:
shape: (5, 2)
┌────────────────┬──────────────┐
│ integer_column ┆ float_column │
│ ---            ┆ ---          │
│ i64            ┆ f64          │
╞════════════════╪══════════════╡
│ 1              ┆ 1.1          │
│ 2              ┆ 2.2          │
│ 3              ┆ 3.3          │
│ 4              ┆ 4.4          │
│ 5              ┆ 5.5          │
└────────────────┴──────────────┘

Data Types:
Schema({'integer_column': Int64, 'float_column': Float64})


In [52]:
df = df.with_columns([
    df["integer_column"].cast(pl.Int32),
    df["float_column"].cast(pl.Float32)
])
 
print("\nUpdated Data Types:")
print(df.schema)


Updated Data Types:
Schema({'integer_column': Int32, 'float_column': Float32})


In [53]:
# For very large numbers, use Int64 or UInt64:
df_large = pl.DataFrame({
    "big_number": [10**12, 10**13, 10**14]  # Large integers
}).with_columns(pl.col("big_number").cast(pl.Int64))
 
print("\nLarge Number Data Types:")
print(df_large.schema)


Large Number Data Types:
Schema({'big_number': Int64})


In [54]:
df = df.with_columns(
    (df["float_column"] * 3.14159).alias("pi_multiplication")
)
 
print("\nResult with Precision:")
print(df)


Result with Precision:
shape: (5, 3)
┌────────────────┬──────────────┬───────────────────┐
│ integer_column ┆ float_column ┆ pi_multiplication │
│ ---            ┆ ---          ┆ ---               │
│ i32            ┆ f32          ┆ f32               │
╞════════════════╪══════════════╪═══════════════════╡
│ 1              ┆ 1.1          ┆ 3.455749          │
│ 2              ┆ 2.2          ┆ 6.911499          │
│ 3              ┆ 3.3          ┆ 10.367248         │
│ 4              ┆ 4.4          ┆ 13.822997         │
│ 5              ┆ 5.5          ┆ 17.278746         │
└────────────────┴──────────────┴───────────────────┘


In [55]:
df.describe()

statistic,integer_column,float_column,pi_multiplication
str,f64,f64,f64
"""count""",5.0,5.0,5.0
"""null_count""",0.0,0.0,0.0
"""mean""",3.0,3.3,10.367248
"""std""",1.581139,1.739253,5.464019
"""min""",1.0,1.1,3.455749
"""25%""",2.0,2.2,6.911499
"""50%""",3.0,3.3,10.367248
"""75%""",4.0,4.4,13.822997
"""max""",5.0,5.5,17.278746
